Initial commit
Forge Broken in Dev because /shrug

1.16.5 doesnt work at all because of something to do with Arch API expecting autoconfig
java.lang.NoClassDefFoundError: me/sargunvohra/mcmods/autoconfig1u/ConfigData